# Generated by Django 5.2.6 on 2025-09-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movive',
        ),
    ]
