# Generated by Django 5.2.6 on 2025-09-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_movie_director_alter_movie_budget_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director_email',
            field=models.EmailField(default='sugar_daddy@gmail.com', max_length=254),
        ),
    ]
