# Generated by Django 5.2.6 on 2025-10-02 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_directors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directors',
            new_name='Director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director_email',
        ),
    ]
