# Generated by Django 5.2.6 on 2025-09-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_best_selling',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
